=== MystFan/TelerikAcademy/Databases/XML basics/students.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="students"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:students"
           xmlns="urn:students"
           elementFormDefault="qualified">

  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="student" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="sex"/>
        <xs:element ref="birth-date"/>
        <xs:element ref="phone"/>
        <xs:element name="e-mail" type="emailAddress"/>
        <xs:element ref="course"/>
        <xs:element ref="specialty"/>
        <xs:element name="faculty-number" type="faculty-number"/>
        <xs:element ref="exams"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="name" type="xs:string"/>
  <xs:element name="sex" type="xs:string"/>
  <xs:element name="birth-date" type="xs:date"/>
  <xs:element name="phone" type="xs:string"/>
  <xs:simpleType name="emailAddress">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^@]+@[^\.]+\..+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="course" type="xs:string"/>
  <xs:element name="specialty" type="xs:string"/>
  <xs:simpleType name="faculty-number">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{7}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="exams">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="exam"  maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required">
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="exam">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="exam-name"/>
        <xs:element ref="score"/>
        <xs:element ref="endorsement"/>
        <xs:element ref ="enrollment-date"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="enrollment-date" type="xs:date"/>
  <xs:element name="exam-name" type="xs:string"/>
  <xs:element name="score" type="xs:double"/>
  <xs:element name="endorsement" type="xs:boolean"/>
</xs:schema>

=== MystFan/TelerikAcademy/Databases/XML basics/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet  type="text/xsl"  href="style.xslt"?>
<students name="Students" xmlns="urn:students" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:students students.xsd">
  <student>
    <name>Doncho Minkov</name>
    <sex>male</sex>
    <birth-date>1995-03-03</birth-date>
    <phone>0878787878</phone>
    <e-mail>DonchoMinkov@gmail.com</e-mail>
    <course>none</course>
    <specialty>Javascript Master(Guru)</specialty>
    <faculty-number>1234567</faculty-number>
    <exams name="Passed exams">
      <exam>
        <exam-name>Javascript Application 2015</exam-name>
        <score>99.9</score>
        <endorsement>true</endorsement>
        <enrollment-date>2015-08-30</enrollment-date>
      </exam>
      <exam>
        <exam-name>C# Part 1</exam-name>
        <score>88.8</score>
        <endorsement>true</endorsement>
        <enrollment-date>2015-01-30</enrollment-date>
      </exam>
    </exams>
  </student>
  <student>
    <name>Niki Kostov</name>
    <sex>male</sex>
    <birth-date>1991-01-02</birth-date>
    <phone>0876576577</phone>
    <e-mail>niki@abv.bg</e-mail>
    <course>JavaScript Basics</course>
    <specialty>developer</specialty>
    <faculty-number>6547567</faculty-number>
    <exams name="Passed exams">
      <exam>
        <exam-name>Databases</exam-name>
        <score>85.5</score>
        <endorsement>true</endorsement>
        <enrollment-date>2015-01-30</enrollment-date>
      </exam>
    </exams>
  </student>
  <student>
    <name>Jhon Doe</name>
    <sex>male</sex>
    <birth-date>1989-01-02</birth-date>
    <phone>0875687878</phone>
    <e-mail>jhonDoe@abv.bg</e-mail>
    <course>JavaScriptOOP</course>
    <specialty>developer</specialty>
    <faculty-number>1232345</faculty-number>
    <exams name="Passed exams">
      <exam>
        <exam-name>Databases</exam-name>
        <score>43.5</score>
        <endorsement>true</endorsement>
        <enrollment-date>2015-01-30</enrollment-date>
      </exam>
    </exams>
  </student>
</students>
