=== MystFan/TelerikAcademy/Databases/Processing XML in .NET/16.CatalogueXSD/xml/catalogue.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="catalogue"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:catalogue"
           xmlns="urn:catalogue"
           elementFormDefault="qualified">

  <xs:element name="albums">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="album" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="album">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="artist"/>
        <xs:element ref="year"/>
        <xs:element name="producer"/>
        <xs:element ref="price"/>
        <xs:element ref="songs"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="name" type="xs:string"/>
  <xs:element name="artist" type="xs:string"/>
  <xs:element name="year">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="(19[789]\d|20[01]\d)"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="producer" type="xs:string"/>
  <xs:element name="price">
    <xs:simpleType>
      <xs:restriction base="xs:double">
        <xs:minInclusive value="0.10"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="songs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="song"  maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="optional">
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="song">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element ref="duration"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="title" type="xs:string"/>
  <xs:element name="duration">
    <xs:simpleType>
      <xs:restriction base="xs:double">
        <xs:minInclusive value="0.30"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

=== MystFan/TelerikAcademy/Databases/Processing XML in .NET/16.CatalogueXSD/xml/catalogue.xml
<?xml version="1.0" encoding="utf-8"?>

<albums name="Catalogue" xmlns="urn:catalogue" 
        xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="urn:catalogue catalogue.xsd">
  
  <album>
    <name>INVADERS MUST DIE</name>
    <artist>THE PRODIGY</artist>
    <year>2009</year>
    <producer>Liam Howlett, James Rushent</producer>
    <price>15</price>
    <songs>
      <song>
        <title>Invaders Must Die</title>
        <duration>2.56</duration>
      </song>
      <song>
        <title>Mescaline </title>
        <duration>4.58</duration>
      </song>
      <song>
        <title>Thunder (Arveene &amp; Misk's Storm-Warning Remix)</title>
        <duration>5.27</duration>
      </song>
      <song>
        <title>Invaders Must Die (Proxy remix)</title>
        <duration>4.03</duration>
      </song>
    </songs>
  </album>
  <album>
    <name>METEORA</name>
    <artist>LINKIN PARK</artist>
    <year>2003</year>
    <producer>Don Gilmor - Warner Brothers</producer>
    <price>12</price>
    <songs>
      <song>
        <title>Foreword Don't Stay</title>
        <duration>3.35</duration>
      </song>
      <song>
        <title>Somewhere I Belong</title>
        <duration>3.37</duration>
      </song>
      <song>
        <title>Lying from You</title>
        <duration>3.00</duration>
      </song>
      <song>
        <title>Hit the Floor</title>
        <duration>2.47</duration>
      </song>
      <song>
        <title>Easier to Run</title>
        <duration>3.30</duration>
      </song>
      <song>
        <title>Faint</title>
        <duration>2.45</duration>
      </song>
      <song>
        <title>Figure.09</title>
        <duration>3.21</duration>
      </song>
      <song>
        <title>Breaking the Habit</title>
        <duration>3.21</duration>
      </song>
      <song>
        <title>From the Inside</title>
        <duration>2.57</duration>
      </song>
      <song>
        <title>Nobody's Listening</title>
        <duration>3.00</duration>
      </song>
      <song>
        <title>Session</title>
        <duration>2.28</duration>
      </song>
      <song>
        <title>Numb</title>
        <duration>3.07</duration>
      </song>
    </songs>
  </album>
  <album>
    <name>MINUTES TO MIDNIGHT</name>
    <artist>LINKIN PARK</artist>
    <year>2009</year>
    <producer>Warner Bros. Records</producer>
    <price>16</price>
    <songs>
      <song>
        <title>Wake</title>
        <duration>1.41</duration>
      </song>
      <song>
        <title>Given Up</title>
        <duration>3.09</duration>
      </song>
      <song>
        <title>Leave Out All the Rest</title>
        <duration>3.29</duration>
      </song>
      <song>
        <title>Bleed It Out</title>
        <duration>2.44</duration>
      </song>
      <song>
        <title>Shadow of the Day</title>
        <duration>4.50</duration>
      </song>
      <song>
        <title>What I've Done</title>
        <duration>3.25</duration>
      </song>
      <song>
        <title>Hands Held High</title>
        <duration>3.53</duration>
      </song>
      <song>
        <title>No More Sorrow</title>
        <duration>3.42</duration>
      </song>
      <song>
        <title>Valentine's Day</title>
        <duration>3.17</duration>
      </song>
      <song>
        <title>In Between</title>
        <duration>3.17</duration>
      </song>
      <song>
        <title>In Pieces</title>
        <duration>3.38</duration>
      </song>
      <song>
        <title>The Little Things Give You Away</title>
        <duration>6.22</duration>
      </song>
    </songs>
  </album>
  <album>
    <name>Recovery</name>
    <artist>EMINEM</artist>
    <year>2010</year>
    <producer> 	Alex da Kid, Boi-1da, Dr. Dre</producer>
    <price>16</price>
    <songs>
      <song>
        <title>Cold Wind Blows</title>
        <duration>5.03</duration>
      </song>
      <song>
        <title>Talkin' 2 Myself</title>
        <duration>5.00</duration>
      </song>
      <song>
        <title>Won't Back Down</title>
        <duration>4.25</duration>
      </song>
      <song>
        <title>On Fire</title>
        <duration>3.33</duration>
      </song>
      <song>
        <title>W.T.P</title>
        <duration>3.58</duration>
      </song>
      <song>
        <title>Going Through Changes</title>
        <duration>4.58</duration>
      </song>
      <song>
        <title>Not Afraid</title>
        <duration>5.00</duration>
      </song>
      <song>
        <title>Seduction</title>
        <duration>4.35</duration>
      </song>
      <song>
        <title>No Love</title>
        <duration>4.59</duration>
      </song>
      <song>
        <title>Space Bound</title>
        <duration>4.38</duration>
      </song>
      <song>
        <title>Cinderella Man</title>
        <duration>4.39</duration>
      </song>
      <song>
        <title>25 to Life</title>
        <duration>4.01</duration>
      </song>
      <song>
        <title>So Bad</title>
        <duration>5.25</duration>
      </song>
      <song>
        <title>Almost Famous</title>
        <duration>4.52</duration>
      </song>
      <song>
        <title>Love the Way You Lie</title>
        <duration>4.23</duration>
      </song>
      <song>
        <title>You're Never Ove</title>
        <duration>5.05</duration>
      </song>
      <song>
        <title>Untitled</title>
        <duration>3.14</duration>
      </song>
    </songs>
  </album>
</albums>
